apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: user-api-selfsigned-cert
spec:
  dnsNames:
    - user-api.grpc-ecommerce
    - localhost
  secretName: user-api-cert-tls
  issuerRef:
    name: ecommerce-selfsigned

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: auth-api-selfsigned-cert
spec:
  dnsNames:
    - auth-api.grpc-ecommerce
    - localhost
  secretName: auth-api-cert-tls
  issuerRef:
    name: ecommerce-selfsigned

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: product-api-selfsigned-cert
spec:
  dnsNames:
    - product-api.grpc-ecommerce
    - localhost
  secretName: product-api-cert-tls
  issuerRef:
    name: ecommerce-selfsigned
