name: Auth API Docker image publish

on:
  push:
    branches:
      - main

    tags:
      - v*

    paths:
      - 'auth-api/**'
      - '.github/workflows/auth-api-publish.yml'

  pull_request:
    paths:
      - 'auth-api/**'

env:
  IMAGE_NAME: ecommerce-auth-api

jobs:
  push:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./auth-api

    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          context: auth-api
          builder: ${{ steps.buildx.outputs.name }}
          push: ${{ github.event_name == 'push' }}
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest
          platforms: linux/amd64,linux/arm64
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest
          cache-to: type=inline

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
